### ISSUE TITLE
wich verison of node

### ISSUE THREAD

**Issue by johnfelipe** [donmccurdy/three-gltf-viewer#294]
install ver 18.x, in sudo and in normal user

but show me this 

	npm ERR! code 1
	npm ERR! path /home/felipe/three-gltf-viewer/node_modules/deasync
	npm ERR! command failed
	npm ERR! command sh -c node ./build.js
	npm ERR! gyp info it worked if it ends with ok
	npm ERR! gyp info using node-gyp@9.0.0
	npm ERR! gyp info using node@18.2.0 | linux | x64
	npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
	npm ERR! gyp http GET https://nodejs.org/download/release/v18.2.0/node-v18.2.0-headers.tar.gz
	npm ERR! gyp http 200 https://nodejs.org/download/release/v18.2.0/node-v18.2.0-headers.tar.gz
	npm ERR! gyp http GET https://nodejs.org/download/release/v18.2.0/SHASUMS256.txt
	npm ERR! gyp http 200 https://nodejs.org/download/release/v18.2.0/SHASUMS256.txt
	npm ERR! gyp info spawn /usr/bin/python3
	npm ERR! gyp info spawn args [
	npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
	npm ERR! gyp info spawn args   'binding.gyp',
	npm ERR! gyp info spawn args   '-f',
	npm ERR! gyp info spawn args   'make',
	npm ERR! gyp info spawn args   '-I',
	npm ERR! gyp info spawn args   '/home/felipe/three-gltf-viewer/node_modules/deasync/build/config.gypi',
	npm ERR! gyp info spawn args   '-I',
	npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
	npm ERR! gyp info spawn args   '-I',
	npm ERR! gyp info spawn args   '/home/felipe/.cache/node-gyp/18.2.0/include/node/common.gypi',
	npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
	npm ERR! gyp info spawn args   '-Dvisibility=default',
	npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/felipe/.cache/node-gyp/18.2.0',
	npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
	npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/felipe/.cache/node-gyp/18.2.0/<(target_arch)/node.lib',
	npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/felipe/three-gltf-viewer/node_modules/deasync',
	npm ERR! gyp info spawn args   '-Dnode_engine=v8',
	npm ERR! gyp info spawn args   '--depth=.',
	npm ERR! gyp info spawn args   '--no-parallel',
	npm ERR! gyp info spawn args   '--generator-output',
	npm ERR! gyp info spawn args   'build',
	npm ERR! gyp info spawn args   '-Goutput_dir=.'
	npm ERR! gyp info spawn args ]
	npm ERR! gyp ERR! build error
	npm ERR! gyp ERR! stack Error: not found: make
	npm ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
	npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
	npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
	npm ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
	npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
	npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
	npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
	npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
	npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
	npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
	npm ERR! gyp ERR! System Linux 5.4.0-110-generic
	npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	npm ERR! gyp ERR! cwd /home/felipe/three-gltf-viewer/node_modules/deasync
	npm ERR! gyp ERR! node -v v18.2.0
	npm ERR! gyp ERR! node-gyp -v v9.0.0
	npm ERR! gyp ERR! not ok
	npm ERR! Build failed

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/felipe/.npm/_logs/2022-05-21T06_53_27_840Z-debug-0.log

**Comment by johnfelipe** [comment]
14
SOLVED
